[tool.poetry]
name = "algobosol_web"
version = "0.1.0"
description = "web interface for algobosol"
authors = ["Sol <misolkim94@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
streamlit = "^1.43.2"
pandas = "^2.2.3"
pyupbit = "^0.2.34"
python-dotenv = "^1.0.0"
sqlalchemy = "^2.0.43"
pydantic = "^2.11.9"

[tool.poetry.group.dev.dependencies]
pytest = "^6.0.0"
pytest-mock = "*"
black = "^25.1.0"
ruff = "^0.9.10"
mypy = "^1.15.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
